# Generated by Django 5.2.4 on 2025-08-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="bot_type",
        ),
        migrations.RemoveField(
            model_name="historicalbot",
            name="bot_type",
        ),
    ]
